config/routes.rb
Rails.application.routes.draw do
  resource :offer, only: [:new, :create]
  root to: 'offers#new'
end

app/models/offer_params.rb
class OfferParams < Struct.new(:uid, :pub0, :page)
	include ActiveModel::Model
	include ActiveModel::Validations

	validates :uid, :page, presence: true

	def self.from_hash(hash)
		new.tap do |obj|
			hash.each {|key,value| obj.send("#{key}=", value)}
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
	def new
		@offer_params = OfferParams.from_hash(page: 1)
	end

	def create
		@offer_params = OfferParams.from_hash(offer_params)
		if @offer_params.valid?
			service = FyberApi::OffersService.new(@offer_params)
			begin
				data = service.fetch_data.with_indifferent_access
				@offers = data['offers']
				render :show
			rescue FyberApi::OffersService::BadRequest
				flash[:error] = "Invalid request. Try again"
				render :new
			end
		else
			render :new
		end
	end

	private
	def offer_params
		params.require(:offer_params).permit(:uid, :page, :pub0)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fyber</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/offers/new.html.haml
= simple_form_for @offer_params, url: offer_path do |f|
	= f.input :uid
	= f.input :pub0
	= f.input :page

	= f.button :submit, 'Find offers'

app/views/offers/show.html.haml
%h1 Offers

- if @offers.empty?
	.no_offers No offers
- else
	- @offers.each do |offer|
		.offer
			.title= offer['title']
			.payout= offer['payout']
			.thumbnail
				= image_tag offer.fetch('thumbnail', {})['lowres']

= link_to 'Back', new_offer_path